### ISSUE TITLE
Executables inside repo - equals a huge repo

### ISSUE THREAD

**Issue by uffejakobsen** [fieserWolF/ditheridoo#3]
Hi,

Having executables inside the repo seems like a really bad idea

Because of this - the repo is already close to 100MB when cloning 
 - and I will guess that it will keep growing in this manner - if this approach continues

Why not use other means of keeping the releases outside the repo ?

**Comment by fieserWolF** [comment]
Thanks for your feedback. I will think about this.

**Comment by fieserWolF** [comment]
I removed the standalone executables. They can now be found at the Releases:
https://github.com/fieserWolF/ditheridoo/releases
