### ISSUE TITLE
Running ditheridoo.py script on Ubuntu fails with import error -> solution

### ISSUE THREAD

**Issue by LucDepauw** [fieserWolF/ditheridoo#4]
Hi, 
Installing pyhton3 as described in the manual and running the python3 script fails with 'ImportError: cannot import name 'ImageTk'.

The complete commandline must be:

`sudo apt-get install python3 python3-tk python3-pil python3-pil.imagetk`

Regards

Luc

**Comment by fieserWolF** [comment]
Thanks! Will update the documentation then.
